---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "30 7 * * 3"

defaults:
  run:
    working-directory: 'caddy_ansible.caddy_ansible'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          # Commented-out OS are too new and suffer from https://github.com/caddy-ansible/caddy-ansible/issues/44
          # so need to fix that before enabling again.
          # - centos8
          - fedora41
          # - ubuntu1804
          # - ubuntu2004
          - ubuntu2204
          # - debian10
          # - debian11
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'caddy_ansible.caddy_ansible'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install wheel package.
        run: pip3 install wheel

      - name: Install requirements.txt dependencies
        run: pip3 install -r requirements.txt

      - name: Install test dependencies.
        run: pip3 install ansible ansible-lint yamllint molecule-plugins[docker,lint] pytest pytest-testinfra

      - name: Install required ansible collections.
        run: ansible-galaxy collection install community.general --upgrade

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          ANSIBLE_VERBOSITY: 3
